#ifndef __AUDIO_H__
#define __AUDIO_H__

#include <PR/libmus.h>

/* =============== MACROS =============== */

#define WBANK_INST1_START	_wbank_inst1SegmentRomStart
#define WBANK_SFX1_START	_wbank_sfx1SegmentRomStart

#define PBANK_INST1_START	_pbank_inst1SegmentRomStart
#define PBANK_INST1_END		_pbank_inst1SegmentRomEnd
#define PBANK_SFX1_START	_pbank_sfx1SegmentRomStart
#define PBANK_SFX1_END		_pbank_sfx1SegmentRomEnd

#define BGM1_START			_bgm1SegmentRomStart
#define BGM1_END			_bgm1SegmentRomEnd
#define SFX1_START			_sfx1SegmentRomStart
#define SFX1_END			_sfx1SegmentRomEnd

// These are automatically generated by spec makefile
extern char WBANK_INST1_START[];
extern char WBANK_SFX1_START[];

extern char PBANK_INST1_START[];
extern char PBANK_INST1_END[];
extern char PBANK_SFX1_START[];
extern char PBANK_SFX1_END[];

extern char BGM1_START[];
extern char BGM1_END[];
extern char SFX1_START[];
extern char SFX1_END[];

/* ============= FUNCTIONS ============== */

extern void init_audio();
extern void load_inst(char *start, char *end, char *wbank);
extern void play_bgm(char *start, char *end);

extern void load_sounds(char *ptr_start, char *ptr_end, char *wbank, char *start, char *end);
extern void play_sound(int index);

#endif