#include <ultra64.h>
#include <PR/libmus.h>

#include "config.h"
#include "helpers/reader.h"
#include "helpers/scheduler.h"

/* ============= PROTOTYPES ============= */

// Sizes taken from NuSystem
#define PTR_BUF_SIZE 0x4000
#define SFX_BUF_SIZE 0x4000
#define BGM_BUF_SIZE 0x4000

static u8 sfx_buf[SFX_BUF_SIZE] __attribute__((aligned(16)));
static u8 ptr_sfx_buf[PTR_BUF_SIZE] __attribute__((aligned(16)));
static u8 bgm_buf[BGM_BUF_SIZE] __attribute__((aligned(16)));
static u8 ptr_inst_buf[PTR_BUF_SIZE] __attribute__((aligned(16)));

/* ============== EXTERNAL ============== */

#define WBANK_INST1_START	_wbank_inst1SegmentRomStart
#define WBANK_SFX1_START	_wbank_sfx1SegmentRomStart

#define PBANK_INST1_START	_pbank_inst1SegmentRomStart
#define PBANK_INST1_END		_pbank_inst1SegmentRomEnd
#define PBANK_SFX1_START	_pbank_sfx1SegmentRomStart
#define PBANK_SFX1_END		_pbank_sfx1SegmentRomEnd

#define BGM1_START			_bgm1SegmentRomStart
#define BGM1_END			_bgm1SegmentRomEnd
#define SFX1_START			_sfx1SegmentRomStart
#define SFX1_END			_sfx1SegmentRomEnd

// These are automatically generated by spec makefile
extern char WBANK_BGM1_START[];
extern char WBANK_SFX1_START[];

extern char PBANK_BGM1_START[];
extern char PBANK_BGM1_END[];
extern char PBANK_SFX1_START[];
extern char PBANK_SFX1_END[];

extern char BGM1_START[];
extern char BGM1_END[];
extern char SFX1_START[];
extern char SFX1_END[];

/* ============= FUNCTIONS ============== */

void init_audio()
{
	musConfig config;

	config.control_flag = 0; // Use ROM wavetables
	config.channels = 24; // Decent default for channel count
	config.sched = &scheduler;
	config.thread_priority = PR_AUDIO;
	// Setup audio heap
	config.heap = (u8 *)AUDIO_ADDR;
	config.heap_length = AUDIO_SIZE;
	// Set FIFO length to minimum
	config.fifo_length = 64;
	// Assign no initial audio or FX bank
	config.ptr = NULL;
	config.wbk = NULL;
	config.default_fxbank = NULL;

	// Set audio default frequency
	config.syn_output_rate = AUDIO_BITRATE;

	// Set synthesizer parameters to sane defaults from nualstl3
	config.syn_updates = 256;
	config.syn_rsp_cmds = 2048;
	config.syn_num_dma_bufs = 64;
	config.syn_dma_buf_size = 1024;
	config.syn_retraceCount = 1; // Must be same as last parameter to osCreateScheduler

	// Initialize libmus
	MusInitialize(&config);
}

void load_inst(char *start, char *end, char *wbank)
{
	// Read and register the instrument bank and its pointers. (instruments ptr file)
	load_binary((void*)start, (void*)ptr_inst_buf, end-start);
	MusPtrBankInitialize(ptr_inst_buf, wbank);
}

void play_bgm(char *start, char *end)
{
	// Read and register the background music (song bin file)
	load_binary((void*)start,(void*)bgm_buf, end-start);

	// Set override for the instrument bank pointers
	MusPtrBankSetSingle(ptr_inst_buf);

	// Play the song utilizing the instruments bank
	MusStartSong(bgm_buf);
}

void load_sounds(char *ptr_start, char *ptr_end, char *wbank, char *start, char *end)
{
	// Read and register the instrument bank and its pointers. (instruments ptr file)
	load_binary((void*)ptr_start, (void*)ptr_sfx_buf, ptr_end-ptr_start);
	MusPtrBankInitialize(ptr_sfx_buf, wbank);

	// Read and register the sound effects. (sound effects bfx file)
	load_binary((void*)start, (void*)sfx_buf, end-start);
	MusFxBankInitialize(sfx_buf);
}

void play_sound(int index)
{
	MusStartEffect(index);
}