#ifndef __READER_H__
#define __READER_H__

// These are automatically generated by spec makefile
#define ROM_START(name)   _ ## name ## SegmentRomStart
#define ROM_END(name)     _ ## name ## SegmentRomEnd
#define ROM_SEGSIZE(name) (ROM_END(name)-ROM_START(name))
#define ROM_SEGMENT(name) extern char _##name##SegmentRomStart[]; \
						  extern char _##name##SegmentRomEnd[];

extern void init_reader();
extern void load_segment(char* seg, char address, char start, char end);
extern void load_binary(void *rom_address, void *ram_buffer, int size);
extern void load_all_segments();

#endif